name: Deploy Web App to Azure Static Web Apps

on:
  push:
    branches: [ "main" ]           # dispara em cada push no main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: [ "main" ]

# ─────────────────────────────────────────────────────────────
# Variáveis globais
env:
  APP_LOCATION: "/"                # raiz do projeto
  API_LOCATION: ""                 # deixe vazio se não usa Azure Functions
  APP_ARTIFACT_LOCATION: "dist"    # pasta gerada pelo WeWeb/Vue
  AZURE_STATIC_WEB_APPS_API_TOKEN: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}

permissions:
  contents: read

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    name: Build and Deploy
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Deploy to Azure Static Web Apps
        id: deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ env.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}      # comenta PRs, etc.
          action: "upload"
          app_location: ${{ env.APP_LOCATION }}
          api_location: ${{ env.API_LOCATION }}
          app_artifact_location: ${{ env.APP_ARTIFACT_LOCATION }}
          skip_app_build: true                         # 👉 já vem pronto em dist, só faça upload

  close_pull_request_job:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    name: Close Pull Request
    steps:
      - uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ env.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "close"
