name: Deploy Web App to Azure Static Web Apps

on:
  push:
    branches: [ "codex/verificar-erros-quebrando-site-em-produção" ]   # ← novo branch
  pull_request:
    types: [ opened, synchronize, reopened, closed ]
    branches: [ "codex/verificar-erros-quebrando-site-em-produção" ]

env:
  APP_LOCATION: "/"          # raiz do front
  API_LOCATION: ""           # vazio se não usa Azure Functions
  APP_ARTIFACT_LOCATION: "dist"
  AZURE_STATIC_WEB_APPS_API_TOKEN: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}

permissions:
  contents: read

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Build & Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ env.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: upload
          app_location: ${{ env.APP_LOCATION }}
          api_location: ${{ env.API_LOCATION }}
          app_artifact_location: ${{ env.APP_ARTIFACT_LOCATION }}
          production_branch: "codex/verificar-erros-quebrando-site-em-produção"   # opcional, mas deixa claro

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps:
      - uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ env.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: close
